//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int id { get; set; }
        public string cmpny_name { get; set; }
        public string cmpny_desc { get; set; }
        public string cmpny_addrss { get; set; }
        public string cmpny_email { get; set; }
        public string cmpny_notes { get; set; }
    }
}
