//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int prod_id { get; set; }
        public string prod_aname { get; set; }
        public string prod_ename { get; set; }
        public Nullable<int> prod_type { get; set; }
        public string prod_desc { get; set; }
        public int prod_status { get; set; }
        public string prod_img { get; set; }
        public string prod_othrs { get; set; }
    }
}
