//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class std_actvties
    {
        public int atv_id { get; set; }
        public string actv_nm { get; set; }
        public Nullable<System.DateTime> actv_strt_dt { get; set; }
        public Nullable<System.DateTime> actv_end_dt { get; set; }
        public string actv_dtls { get; set; }
        public Nullable<int> actv_std_no { get; set; }
        public string actv_std_nm_lst { get; set; }
        public Nullable<int> actv_dgre { get; set; }
        public string actv_dgre_note { get; set; }
        public string actv_about { get; set; }
        public string actv_suprvisor { get; set; }
        public Nullable<int> actv_status { get; set; }
    }
}
