//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stor
    {
        public int str_id { get; set; }
        public string str_name { get; set; }
        public string str_location { get; set; }
        public string str_desc { get; set; }
        public Nullable<int> str_status { get; set; }
        public Nullable<System.DateTime> str_opn_dt { get; set; }
        public Nullable<System.DateTime> str_cls_dt { get; set; }
        public Nullable<int> str_usr_id { get; set; }
    }
}
