//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class storOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public storOrder()
        {
            this.StorOrderDetails = new HashSet<StorOrderDetail>();
        }
    
        public int ordr_id { get; set; }
        public int str_id { get; set; }
        public Nullable<System.DateTime> ordr_dt { get; set; }
        public Nullable<int> ordr_usr { get; set; }
        public string ordr_dsc { get; set; }
        public int ordr_type { get; set; }
        public int ordr_status { get; set; }
        public Nullable<int> add_by { get; set; }
        public Nullable<System.DateTime> add_at { get; set; }
        public Nullable<int> updt_by { get; set; }
        public Nullable<System.DateTime> updt_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorOrderDetail> StorOrderDetails { get; set; }
    }
}
