//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorProduct
    {
        public int rec_ser { get; set; }
        public int str_id { get; set; }
        public int prod_id { get; set; }
        public int prod_QT { get; set; }
        public Nullable<System.DateTime> prod_add_dt { get; set; }
        public Nullable<System.DateTime> prod_updt_dt { get; set; }
        public Nullable<int> prod_bill_id { get; set; }
        public string prod_othrs { get; set; }
        public Nullable<int> add_by { get; set; }
        public Nullable<int> updtd_by { get; set; }
        public Nullable<int> aprovd_by { get; set; }
    }
}
