//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorOrderDetail
    {
        public int rec_ser { get; set; }
        public int ordr_id { get; set; }
        public int prod_id { get; set; }
        public int prod_qt { get; set; }
    
        public virtual storOrder storOrder { get; set; }
    }
}
