//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysFlag
    {
        public int flg_id { get; set; }
        public string flg_code { get; set; }
        public int flg_value { get; set; }
        public string flg_desc { get; set; }
        public Nullable<int> flg_status { get; set; }
        public string flg_about { get; set; }
    }
}
