//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnr
    {
        public int trnr_id { get; set; }
        public string trnr_nm { get; set; }
        public string trnr_exp { get; set; }
        public string trnr_major { get; set; }
        public string trnr_about { get; set; }
        public string trnr_phn { get; set; }
        public Nullable<int> trnr_status { get; set; }
    }
}
