//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public string user_login { get; set; }
        public string user_pass { get; set; }
        public string user_name { get; set; }
        public string user_role { get; set; }
        public Nullable<int> user_status { get; set; }
        public string user_img { get; set; }
    }
}
