//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VStorOrdrsOnly
    {
        public int ordr_id { get; set; }
        public int str_id { get; set; }
        public Nullable<System.DateTime> ordr_dt { get; set; }
        public Nullable<int> ordr_usr { get; set; }
        public string ordr_dsc { get; set; }
        public string ordr_status_name { get; set; }
        public string ordr_typ_name { get; set; }
        public int ordr_type { get; set; }
        public int ordr_status { get; set; }
        public string str_name { get; set; }
    }
}
