//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorSystem.SysData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VStorProduct
    {
        public string prod_aname { get; set; }
        public string prod_ename { get; set; }
        public string prod_desc { get; set; }
        public decimal prod_dflt_price { get; set; }
        public string type_name { get; set; }
        public int str_id { get; set; }
        public int prod_QT { get; set; }
        public decimal prod_price { get; set; }
        public Nullable<System.DateTime> prod_add_dt { get; set; }
        public string prod_othrs { get; set; }
        public string str_name { get; set; }
        public string catgry_name { get; set; }
    }
}
